from datetime import datetime
from pydantic import BaseModel, ConfigDict

# ------------------------------------------------------------------------------
# SHIPMENT SCHEMAS
# ------------------------------------------------------------------------------
class ShipmentCreate(BaseModel):
    """
    Schema representing the input fields required to create a shipment.
    All fields are required.
    """
    source: str
    destination: str
    current_lat: float
    current_lng: float
    distance: float
    eta: str


class ShipmentResponse(ShipmentCreate):
    """
    Schema representing the structure of a shipment returned from the API.
    Includes the database ID, the current status, and the computed delay probability.
    """
    id: int
    status: str
    delay_probability: float
    original_eta: str | None = None
    current_eta: str | None = None

    # ConfigDict(from_attributes=True) allows Pydantic to read ORM models directly
    model_config = ConfigDict(from_attributes=True)


# ------------------------------------------------------------------------------
# REGION SCHEMAS
# ------------------------------------------------------------------------------
class RegionCreate(BaseModel):
    """
    Schema representing the input fields required to create or configure a geographical region.
    """
    region_name: str
    weather_score: float
    traffic_score: float
    warehouse_score: float


class RegionResponse(RegionCreate):
    """
    Schema representing the structure of a region returned from the API.
    Includes the database ID and the calculated aggregate risk score.
    """
    id: int
    risk_score: float

    model_config = ConfigDict(from_attributes=True)


# ------------------------------------------------------------------------------
# WAREHOUSE SCHEMAS
# ------------------------------------------------------------------------------
class WarehouseCreate(BaseModel):
    """
    Schema representing the input fields required to configure a warehouse.
    """
    warehouse_name: str
    capacity: int
    current_load: int


class WarehouseResponse(WarehouseCreate):
    """
    Schema representing the structure of a warehouse returned from the API.
    Includes the database ID and the calculated capacity utilization.
    """
    id: int
    utilization: float

    model_config = ConfigDict(from_attributes=True)


# ------------------------------------------------------------------------------
# ALERT SCHEMAS
# ------------------------------------------------------------------------------
class AlertResponse(BaseModel):
    """
    Schema representing an alert notification generated by the system.
    """
    id: int
    shipment_id: int
    message: str
    severity: str
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)
